/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.sql.Array;
import java.util.Arrays;
import java.util.Random;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        Reader reader = new FileReader("./app/src/main/resources/recentquotes.json");
        Book[] b = gson.fromJson(reader, Book[].class);
        Random rand = new Random();
        int randomNum = rand.nextInt((b.length ) + 1);
        System.out.println(gson.toJson(b[randomNum]));



    }
}
